const LOAD_RESULTS = "LOAD_RESULTS";
const LOAD_CURRENT_PAGE = "LOAD_CURRENT_PAGE";

const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
const FILTER_BY_FROM_API = "FILTER_BY_FROM_API";
const FILTER_BY_FROM_USER = "FILTER_BY_FROM_USER";

const ORDER_BY_ALPHA_ASC = "ORDER_BY_ALPHA_ASC";
const ORDER_BY_ALPHA_DESC = "ORDER_BY_ALPHA_DESC";
const ORDER_BY_MIN_TO_MAX_WEIGHT = "ORDER_BY_MIN_TO_MAX_WEIGHT";
const ORDER_BY_MAX_TO_MIN_WEIGHT = "ORDER_BY_MAX_TO_MIN_WEIGHT";

const GO_TO_N_PAGE = "GO_TO_N_PAGE";

const GET_BREED_DETAILS = "GET_BREED_DETAILS";

const ADD_BREED_TO_DATABASE = "ADD_BREED_TO_DATABASE";
const BREED_NOT_ADDED_TO_DATABASE = "BREED_NOT_ADDED_TO_DATABASE";

module.exports ={
  LOAD_RESULTS,
  LOAD_CURRENT_PAGE,
  FILTER_BY_TEMPERAMENT,
  FILTER_BY_FROM_API,
  FILTER_BY_FROM_USER,
  ORDER_BY_ALPHA_ASC,
  ORDER_BY_ALPHA_DESC,
  ORDER_BY_MIN_TO_MAX_WEIGHT,
  ORDER_BY_MAX_TO_MIN_WEIGHT,
  GO_TO_N_PAGE,
  GET_BREED_DETAILS,
  ADD_BREED_TO_DATABASE,
  BREED_NOT_ADDED_TO_DATABASE
};